PUMP_LOG = "cache/pumplog.json"
CHARGE_LOG = "cache/chargelog.json"
FAN_LOG = "cache/fanlog.json"
SYSCONFIG = "cache/config.json"

PUMP_GPIO = 1
PUMP_RUNTIME = 15
PUMP_RUN_INTERVAL = 86400

FAN_GPIO = 4
TEMP_POLL_INTERVAL = 60
TEMP_UPPER_LIMIT = 55
TEMP_COOLDOWN = 45

CHARGER_GPIO = 2
CHARGER_RUNTIME = 10800
CHARGER_OFFTIME = 10800